# Generated by Django 3.2.9 on 2022-10-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=20000)),
                ('image', models.ImageField(upload_to='')),
                ('last_updated', models.DateTimeField(verbose_name='last updated')),
            ],
        ),
    ]
