# Generated by Django 3.2.9 on 2022-10-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon_colour',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
